version: 2
project_name: deploy

builds:
  - main: .
    binary: deploy
    ldflags:
      - -s -w
      - -X deploy/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "linux" }}linux
      {{- else if eq .Os "darwin" }}darwin
      {{- end }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{.Version}}-SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
