#!/bin/bash
set -e

# ──────────────────────────────────────────────────────────────────────────────
#  deploy — single-server personal PaaS
#  A minimal deployment tool: register apps, auto-assign ports, generate nginx
#  reverse proxy config with SSL, manage processes.
#
#  Usage:  deploy <command> [options]
#  See:    deploy help
# ──────────────────────────────────────────────────────────────────────────────

# ── Config ───────────────────────────────────────────────────────────────────
# All configurable via env vars or config file.
# Config file search order: $DEPLOY_CONF → ~/.deploy/deploy.conf → /etc/deploy.conf

DEPLOY_HOME="${DEPLOY_HOME:-$HOME/.deploy}"
DEPLOY_CONF="${DEPLOY_CONF:-$DEPLOY_HOME/deploy.conf}"

# Load config file if it exists
if [ -f "$DEPLOY_CONF" ]; then
  source "$DEPLOY_CONF"
elif [ -f "$HOME/.deploy/deploy.conf" ]; then
  source "$HOME/.deploy/deploy.conf"
elif [ -f "/etc/deploy.conf" ]; then
  source "/etc/deploy.conf"
fi

# Configuration (with defaults)
REGISTRY="${REGISTRY:-$DEPLOY_HOME/registry}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/sites-available/deploy}"
BASE_DOMAIN="${BASE_DOMAIN:-example.com}"
SSL_CERT="${SSL_CERT:-}"
SSL_KEY="${SSL_KEY:-}"
CUSTOM_DIR="${CUSTOM_DIR:-$DEPLOY_HOME/nginx-custom}"
LOG_DIR="${LOG_DIR:-$DEPLOY_HOME/logs}"
MIN_PORT="${MIN_PORT:-8000}"
MAX_PORT="${MAX_PORT:-9000}"

# Ensure directories exist
mkdir -p "$DEPLOY_HOME" "$CUSTOM_DIR" "$LOG_DIR"
[ ! -f "$REGISTRY" ] && touch "$REGISTRY"

# ── Helpers ───────────────────────────────────────────────────────────────────

get_app_port() { grep "^$1\t" "$REGISTRY" | awk '$4=="app" {print $2}' | head -1; }
get_type()     { grep "^$1\t" "$REGISTRY" | awk '$4=="app" {print $3}' | head -1; }
get_path()     { grep "^$1\t" "$REGISTRY" | awk '$4=="app" {print $5}' | head -1; }

next_port() {
  port=$MIN_PORT
  while grep -qP "^\S+\t$port\t" "$REGISTRY" 2>/dev/null || lsof -ti :"$port" &>/dev/null; do
    ((port++))
    if [ "$port" -gt "$MAX_PORT" ]; then
      echo "Error: no ports available in range $MIN_PORT-$MAX_PORT" >&2
      exit 1
    fi
  done
  echo "$port"
}

# Detect nginx config type based on SSL
nginx_listen_block() {
  if [ -n "$SSL_CERT" ] && [ -n "$SSL_KEY" ]; then
    echo "    listen 443 ssl;"
    echo "    ssl_certificate ${SSL_CERT};"
    echo "    ssl_certificate_key ${SSL_KEY};"
  else
    echo "    # SSL not configured — set SSL_CERT and SSL_KEY"
  fi
}

default_server_block() {
  local name=$1
  local port=$2
  cat << BLOCK

server {
    server_name ${name}.${BASE_DOMAIN};
    listen 80;
$(nginx_listen_block)

    location / {
        proxy_pass http://127.0.0.1:${port}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering off;
        proxy_read_timeout 120s;
    }
}
BLOCK
}

regen_nginx() {
  local reset=false
  [ "$1" == "--reset" ] && reset=true

  echo "Regenerating nginx config..."
  cat > /tmp/deploy_nginx << 'NGINXEOF'
# Auto-generated by deploy
NGINXEOF

  grep -v '^#' "$REGISTRY" | grep -v '^$' | awk '$4=="app" {print $1, $2}' | sort -u | while read -r name port; do
    custom_file="${CUSTOM_DIR}/${name}.conf"

    if [ "$reset" == "false" ] && [ -f "$custom_file" ]; then
      echo "  → using custom block for $name"
      cat "$custom_file" >> /tmp/deploy_nginx
    else
      default_server_block "$name" "$port" >> /tmp/deploy_nginx
    fi
  done

  sudo cp /tmp/deploy_nginx "$NGINX_CONF"
  sudo nginx -t && sudo nginx -s reload
}

print_usage() {
  cat << 'EOF'
Usage: deploy <command> [options]

Commands:
  list                          Show all apps and their status
  add <name> <type> <path>      Register a new app (auto-assigns port)
  remove <name>                 Unregister an app
  start <name> [-d]             Start an app (-d for background)
  stop <name>                   Stop an app
  restart <name>                Restart an app
  logs <name>                   Tail app logs
  prod <name>                   Deploy via docker compose
  nginx [--reset]               Regenerate nginx config
  custom <name>                 Create/edit custom nginx snippet
  init                          Create default config and directories
  help                          Show this message

Types: laravel | flask | node | static | docker

Environment variables:
  DEPLOY_HOME      Working directory (default: ~/.deploy)
  REGISTRY         App registry file path
  BASE_DOMAIN      Domain suffix for subdomains (default: example.com)
  SSL_CERT         Path to SSL certificate (optional)
  SSL_KEY          Path to SSL key (optional)
  NGINX_CONF       Output nginx config path
  MIN_PORT         Minimum port number (default: 8000)
  MAX_PORT         Maximum port number (default: 9000)

Config file:
  Settings can be placed in $DEPLOY_CONF, ~/.deploy/deploy.conf,
  or /etc/deploy.conf as VARIABLE=value lines.

Examples:
  deploy init
  deploy add myapp flask /home/user/myapp
  deploy start myapp -d
  deploy list
EOF
}

# ── Commands ──────────────────────────────────────────────────────────────────

case "$1" in
  init)
    mkdir -p "$DEPLOY_HOME" "$CUSTOM_DIR" "$LOG_DIR"
    [ ! -f "$REGISTRY" ] && touch "$REGISTRY"
    if [ ! -f "$DEPLOY_CONF" ]; then
      cat > "$DEPLOY_CONF" << CONF
# deploy configuration
# BASE_DOMAIN=myapp.com
# SSL_CERT=/etc/ssl/certs/myapp.crt
# SSL_KEY=/etc/ssl/private/myapp.key
# NGINX_CONF=/etc/nginx/sites-available/deploy
# MIN_PORT=8000
# MAX_PORT=9000
CONF
      echo "Created $DEPLOY_CONF"
    fi
    echo "Initialized deploy in $DEPLOY_HOME"
    ;;

  list)
    printf "\n%-15s %-6s %-10s %-8s %-40s %s\n" "APP" "PORT" "TYPE" "ROLE" "ENDPOINT" "STATUS"
    echo "──────────────────────────────────────────────────────────────────────────────────"
    while IFS= read -r line; do
      [[ "$line" =~ ^# || -z "$line" ]] && continue
      name=$(echo "$line" | awk '{print $1}')
      port=$(echo "$line" | awk '{print $2}')
      type=$(echo "$line" | awk '{print $3}')
      role=$(echo "$line" | awk '{print $4}')
      if [ "$role" = "app" ]; then
        endpoint="https://${name}.${BASE_DOMAIN}"
        pid=$(lsof -ti :"$port" 2>/dev/null)
        [ -n "$pid" ] && status="running" || status="stopped"
      else
        endpoint=""
        status=""
      fi
      printf "%-15s %-6s %-10s %-8s %-40s %s\n" "$name" "$port" "$type" "$role" "$endpoint" "$status"
    done < "$REGISTRY"
    echo ""
    ;;

  add)
    name=$2; type=$3; path=$4
    [ -z "$name" ] && echo "Usage: deploy add <name> <type> <path>" && exit 1
    [ -z "$type" ] && echo "Usage: deploy add <name> <type> <path>" && exit 1
    [ -z "$path" ] && echo "Usage: deploy add <name> <type> <path>" && exit 1
    [ ! -d "$path" ] && echo "Error: directory not found: $path" && exit 1
    if grep -q "^$name\t" "$REGISTRY" 2>/dev/null; then
      echo "Error: app '$name' already exists"
      exit 1
    fi
    port=$(next_port)
    printf "%s\t%s\t%s\tapp\t%s\n" "$name" "$port" "$type" "$path" >> "$REGISTRY"
    echo "Registered $name on port $port → https://$name.$BASE_DOMAIN"
    regen_nginx
    ;;

  remove)
    name=$2
    [ -z "$name" ] && echo "Usage: deploy remove <name>" && exit 1
    grep -q "^$name\t" "$REGISTRY" 2>/dev/null || { echo "App '$name' not found"; exit 1; }
    sed -i "/^$(echo "$name" | sed 's/[\/&]/\\&/g')\t/d" "$REGISTRY"
    echo "Removed $name"
    regen_nginx
    ;;

  start)
    name=$2
    [ -z "$name" ] && echo "Usage: deploy start <name> [-d]" && exit 1
    daemonize=false
    [ "$3" == "-d" ] && daemonize=true

    port=$(get_app_port "$name")
    type=$(get_type "$name")
    path=$(get_path "$name")
    [ -z "$port" ] && echo "Error: app '$name' not found" && exit 1
    [ -z "$path" ] && echo "Error: path not found for '$name'" && exit 1
    cd "$path" || exit 1

    log_file="${LOG_DIR}/${name}.log"

    case $type in
      laravel) CMD="php artisan serve --host=0.0.0.0 --port=$port" ;;
      flask)   CMD="flask run --host=0.0.0.0 --port=$port" ;;
      node)    CMD="PORT=$port npm start" ;;
      static)  CMD="npx serve -s . -l $port" ;;
      docker)  CMD="docker compose up" ;;
      *)       echo "Unknown type: $type (supported: laravel, flask, node, static, docker)"; exit 1 ;;
    esac

    if $daemonize; then
      nohup bash -c "$CMD" > "$log_file" 2>&1 &
      echo "Started $name (PID $!) in background → https://$name.$BASE_DOMAIN"
      echo "Logs: tail -f $log_file"
    else
      eval "$CMD"
    fi
    ;;

  stop)
    name=$2
    [ -z "$name" ] && echo "Usage: deploy stop <name>" && exit 1
    port=$(get_app_port "$name")
    [ -z "$port" ] && echo "App '$name' not found" && exit 1
    pid=$(lsof -ti :"$port")
    if [ -n "$pid" ]; then
      kill "$pid" && echo "Stopped $name" || echo "Failed to stop $name"
    else
      echo "$name not running"
    fi
    ;;

  restart)
    "$0" stop "$2"
    sleep 1
    "$0" start "$2" -d
    ;;

  logs)
    name=$2
    [ -z "$name" ] && echo "Usage: deploy logs <name>" && exit 1
    log_file="${LOG_DIR}/${name}.log"
    if [ ! -f "$log_file" ]; then
      echo "No logs found for $name"
      exit 1
    fi
    tail -f "$log_file"
    ;;

  prod)
    name=$2
    [ -z "$name" ] && echo "Usage: deploy prod <name>" && exit 1
    path=$(get_path "$name")
    [ -z "$path" ] && echo "App '$name' not found" && exit 1
    cd "$path" && docker compose up --build -d
    echo "Deployed $name → https://$name.$BASE_DOMAIN"
    ;;

  nginx)
    regen_nginx "$2"
    ;;

  custom)
    name=$2
    [ -z "$name" ] && echo "Usage: deploy custom <appname>" && exit 1

    mkdir -p "$CUSTOM_DIR"
    custom_file="${CUSTOM_DIR}/${name}.conf"
    port=$(get_app_port "$name")

    if [ ! -f "$custom_file" ]; then
      echo "Creating custom snippet for $name..."
      default_server_block "$name" "$port" > "$custom_file"
    fi

    echo "Edit with: nano $custom_file"
    echo "Then: deploy nginx"
    ;;

  help|--help|-h)
    print_usage
    ;;

  *)
    if [ -z "$1" ]; then
      print_usage
    else
      echo "Unknown command: $1"
      echo "Run 'deploy help' for usage."
      exit 1
    fi
    ;;
esac
