#!/bin/bash
# deploy/lib/core.sh — Configuration, colors, helpers, nginx functions

# ── ANSI colors ──────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'
ok()   { echo -e " ${GREEN}[ok]${NC} $1"; }
info() { echo -e " ${CYAN}[..]${NC} $1"; }
warn() { echo -e " ${YELLOW}[!!]${NC} $1"; }
err()  { echo -e " ${RED}[!!]${NC} $1" >&2; }

# ── Config ───────────────────────────────────────────────────────────────────
DEPLOY_HOME="${DEPLOY_HOME:-$HOME/.deploy}"
DEPLOY_CONF="${DEPLOY_CONF:-$DEPLOY_HOME/deploy.conf}"

# Load config file if it exists
if [ -f "$DEPLOY_CONF" ]; then
  source "$DEPLOY_CONF"
elif [ -f "$HOME/.deploy/deploy.conf" ]; then
  source "$HOME/.deploy/deploy.conf"
elif [ -f "/etc/deploy.conf" ]; then
  source "/etc/deploy.conf"
fi

# Configuration (with defaults)
REGISTRY="${REGISTRY:-$DEPLOY_HOME/registry}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/sites-available/deploy}"
BASE_DOMAIN="${BASE_DOMAIN:-example.com}"
SSL_CERT="${SSL_CERT:-}"
SSL_KEY="${SSL_KEY:-}"
CUSTOM_DIR="${CUSTOM_DIR:-$DEPLOY_HOME/nginx-custom}"
LOG_DIR="${LOG_DIR:-$DEPLOY_HOME/logs}"
ENV_DIR="${ENV_DIR:-$DEPLOY_HOME/env}"
RELEASES_DIR="${RELEASES_DIR:-$DEPLOY_HOME/releases}"
MIN_PORT="${MIN_PORT:-8000}"
MAX_PORT="${MAX_PORT:-9000}"
HEALTH_RETRIES="${HEALTH_RETRIES:-30}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-1}"

# Ensure directories exist
mkdir -p "$DEPLOY_HOME" "$CUSTOM_DIR" "$LOG_DIR" "$ENV_DIR" "$RELEASES_DIR"
[ ! -f "$REGISTRY" ] && touch "$REGISTRY"

# ── Helpers ───────────────────────────────────────────────────────────────────
get_app_port() { grep "^$1\t" "$REGISTRY" | awk '$4=="app" {print $2}' | head -1; }
get_type()     { grep "^$1\t" "$REGISTRY" | awk '$4=="app" {print $3}' | head -1; }
get_path()     { grep "^$1\t" "$REGISTRY" | awk '$4=="app" {print $5}' | head -1; }
get_pid()      { local p; p=$(lsof -ti :"$(get_app_port "$1")" 2>/dev/null); echo "${p:-}"; }
is_running()   { [ -n "$(get_pid "$1")" ]; }

next_port() {
  port=$MIN_PORT
  while grep -qP "^\S+\t$port\t" "$REGISTRY" 2>/dev/null || lsof -ti :"$port" &>/dev/null; do
    ((port++))
    if [ "$port" -gt "$MAX_PORT" ]; then
      err "no ports available in range $MIN_PORT-$MAX_PORT"
      exit 1
    fi
  done
  echo "$port"
}

# ── Nginx ─────────────────────────────────────────────────────────────────────
nginx_listen_block() {
  if [ -n "$SSL_CERT" ] && [ -n "$SSL_KEY" ]; then
    echo "    listen 443 ssl;"
    echo "    ssl_certificate ${SSL_CERT};"
    echo "    ssl_certificate_key ${SSL_KEY};"
  else
    echo "    # SSL not configured — set SSL_CERT and SSL_KEY"
  fi
}

default_server_block() {
  local name=$1 port=$2
  cat << BLOCK

server {
    server_name ${name}.${BASE_DOMAIN};
    listen 80;
$(nginx_listen_block)

    location / {
        proxy_pass http://127.0.0.1:${port}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering off;
        proxy_read_timeout 120s;
    }
}
BLOCK
}

regen_nginx() {
  local reset=false
  [ "$1" == "--reset" ] && reset=true

  info "regenerating nginx config..."
  cat > /tmp/deploy_nginx << 'NGINXEOF'
# Auto-generated by deploy
NGINXEOF

  grep -v '^#' "$REGISTRY" | grep -v '^$' | awk '$4=="app" {print $1, $2}' | sort -u | while read -r name port; do
    custom_file="${CUSTOM_DIR}/${name}.conf"
    if [ "$reset" == "false" ] && [ -f "$custom_file" ]; then
      info "using custom block for $name"
      cat "$custom_file" >> /tmp/deploy_nginx
    else
      default_server_block "$name" "$port" >> /tmp/deploy_nginx
    fi
  done

  sudo cp /tmp/deploy_nginx "$NGINX_CONF"
  if sudo nginx -t 2>/dev/null; then
    sudo nginx -s reload && ok "nginx reloaded"
  else
    err "nginx config test failed"
    exit 1
  fi
}

health_check() {
  local name=$1 port=$2 retries=$3 interval=$4
  local url="http://127.0.0.1:${port}/"
  for i in $(seq 1 "$retries"); do
    if curl -sf -o /dev/null "$url" 2>/dev/null; then
      ok "$name responded after ${i}s"
      return 0
    fi
    sleep "$interval"
  done
  warn "$name did not respond within $((retries * interval))s — continuing anyway"
  return 1
}

# ── Usage ────────────────────────────────────────────────────────────────────
print_usage() {
  cat << 'EOF'
Usage: deploy <command> [options]

Commands:
  list                          Show all apps and their status
  add <name> <type> <path>      Register a new app (auto-assigns port)
  remove <name>                 Unregister an app
  start <name> [-d]             Start an app (-d for background)
  stop <name>                   Stop an app
  restart <name>                Restart an app
  logs <name>                   Tail app logs
  info <name>                   Show app details
  prod <name>                   Build and deploy via Docker Compose
  nginx [--reset]               Regenerate nginx config
  custom <name>                 Create/edit custom nginx snippet
  config:set <name> KEY=VAL     Set an environment variable
  config:get <name> [KEY]       List all or one env var
  config:unset <name> KEY       Remove an environment variable
  config:encrypt <name>         Encrypt env file with GPG
  config:decrypt <name>         Decrypt env file with GPG
  rollback <name>               Rollback to previous deployment
  ssl <name>                    Provision Let's Encrypt SSL (requires certbot)
  ssl:renew <name>              Renew Let's Encrypt SSL
  uninstall                     Remove all apps and deploy data
  init                          Create default config and directories
  help                          Show this message

Types: laravel | flask | node | static | docker

Environment variables:
  DEPLOY_HOME      Working directory (default: ~/.deploy)
  REGISTRY         App registry file path
  BASE_DOMAIN      Domain suffix for subdomains (default: example.com)
  SSL_CERT         Path to SSL certificate (optional)
  SSL_KEY          Path to SSL key (optional)
  NGINX_CONF       Output nginx config path
  MIN_PORT         Minimum port number (default: 8000)
  MAX_PORT         Maximum port number (default: 9000)

Config file:
  Settings can be placed in $DEPLOY_CONF, ~/.deploy/deploy.conf,
  or /etc/deploy.conf as VARIABLE=value lines.

Examples:
  deploy init
  deploy add myapp flask /home/user/myapp
  deploy config:set myapp DATABASE_URL=postgres://...
  deploy start myapp -d
  deploy list
EOF
}
