#!/bin/bash
# deploy/lib/infra.sh — Infrastructure management

cmd_init() {
  mkdir -p "$DEPLOY_HOME" "$CUSTOM_DIR" "$LOG_DIR" "$ENV_DIR" "$PID_DIR" "$APPS_DIR"
  [ ! -f "$REGISTRY" ] && touch "$REGISTRY"
  if [ ! -f "$DEPLOY_CONF" ]; then
    cat > "$DEPLOY_CONF" << CONF
# deploy configuration
BASE_DOMAIN=example.com
DEV_DOMAIN=dev.example.com
# DNS provider (optional): cloudflare or manual
# DNS_PROVIDER=cloudflare
# CLOUDFLARE_TOKEN=your_api_token
# CLOUDFLARE_ZONE=example.com
# SSL_CERT=/etc/ssl/certs/myapp.crt
# SSL_KEY=/etc/ssl/private/myapp.key
# NGINX_CONF=/etc/nginx/sites-available/deploy
# NGINX_DEV_CONF=/etc/nginx/sites-available/deploy-dev
# MIN_PORT=8000
# MAX_PORT=9000
CONF
    ok "created $DEPLOY_CONF"
  fi
  ok "initialized deploy in $DEPLOY_HOME"
}

cmd_dev() {
  local name=$1
  [ -z "$name" ] && { err "Usage: deploy dev <name>"; exit 1; }
  local path=$(get_path "$name")
  local type=$(get_type "$name")
  local port=$(get_app_port "$name")
  [ -z "$port" ] && { err "app '$name' not found"; exit 1; }
  [ -z "$path" ] && { err "path not found for '$name'"; exit 1; }

  local dev_port
  dev_port=$(get_dev_port "$name")

  cd "$path" || exit 1
  log_file="${LOG_DIR}/${name}.dev.log"
  load_env "$name"

  info "starting $name in dev mode..."
  info "  Dev URL:  https://${name}.${DEV_DOMAIN}"
  info "  Dev port: ${dev_port}"

  # Determine dev command
  local cmd=""
  if [ -f "$path/deploy.yml" ]; then
    cmd=$(parse_yml_value "$path/deploy.yml" "dev")
    cmd="${cmd/\$PORT/$dev_port}"
  fi
  if [ -z "$cmd" ]; then
    case $type in
      laravel) cmd="php artisan serve --host=0.0.0.0 --port=$dev_port" ;;
      flask)   cmd="flask run --debug --host=0.0.0.0 --port=$dev_port" ;;
      node)    cmd="PORT=$dev_port npm run dev 2>/dev/null || PORT=$dev_port npm start" ;;
      static)  cmd="npx serve -s . -l $dev_port --no-clipboard" ;;
      docker)  cmd="PORT=$dev_port docker compose up --build -d" ;;
      *)       cmd="PORT=$dev_port npm start" ;;
    esac
  fi

  # Store dev port
  set_app_field "$name" "dev_port" "$dev_port"
  set_app_field "$name" "dev" "true"

  # Stop existing dev if running
  local existing_pid
  existing_pid=$(lsof -ti :"$dev_port" 2>/dev/null)
  [ -n "$existing_pid" ] && kill "$existing_pid" 2>/dev/null

  nohup bash -c "$cmd" > "$log_file" 2>&1 &
  local bg_pid=$!

  # Wait for port
  sleep 2
  local real_pid
  real_pid=$(lsof -ti :"$dev_port" 2>/dev/null | head -1)
  save_pid "${name}-dev" "${real_pid:-$bg_pid}"

  # Create DNS record for dev subdomain
  if [ -n "$DNS_PROVIDER" ]; then
    dns_add_record "${name}.${DEV_DOMAIN}" "A" ""
  fi

  # Generate dev nginx config
  local ws="${yml_websocket:-false}"
  if [ -z "$ws" ] || [ "$ws" = "false" ]; then
    local ws_val
    ws_val=$(get_app_field "$name" "websocket" 2>/dev/null)
    [ "$ws_val" = "true" ] && ws="true"
  fi

  # Append dev server block to nginx dev config
  dev_server_block "$name" "$dev_port" "$ws" >> /tmp/deploy_nginx_dev

  ok "dev mode started for $name (PID ${real_pid:-$bg_pid})"
  echo "  URL:  https://${name}.${DEV_DOMAIN}"
  echo "  Logs: tail -f $log_file"
  echo "  Stop: deploy stop $name"
}

# Regenerate dev nginx config
regen_dev_nginx() {
  info "regenerating dev nginx config..."
  cat > /tmp/deploy_nginx_dev << 'NGINXEOF'
# Auto-generated by deploy (dev config)
NGINXEOF

  # Collect all dev apps and generate their server blocks
  while IFS= read -r line; do
    [[ "$line" =~ ^# || -z "$line" ]] && continue
    name=$(echo "$line" | awk '{print $1}')
    local dev_enabled
    dev_enabled=$(get_app_field "$name" "dev" 2>/dev/null)
    if [ "$dev_enabled" = "true" ]; then
      local dev_port
      dev_port=$(get_app_field "$name" "dev_port" 2>/dev/null)
      local ws_val
      ws_val=$(get_app_field "$name" "websocket" 2>/dev/null)
      [ -z "$dev_port" ] && continue
      dev_server_block "$name" "$dev_port" "${ws_val:-false}" >> /tmp/deploy_nginx_dev
    fi
  done < "$REGISTRY"

  sudo cp /tmp/deploy_nginx_dev "$NGINX_DEV_CONF"
  if sudo nginx -t 2>/dev/null; then
    sudo nginx -s reload && ok "dev nginx reloaded"
  else
    err "dev nginx config test failed"
    # Don't exit — main nginx should still work
  fi
}

cmd_prod() {
  local name=$1
  [ -z "$name" ] && { err "Usage: deploy prod <name>"; exit 1; }
  path=$(get_path "$name")
  [ -z "$path" ] && { err "app '$name' not found"; exit 1; }

  cd "$path"
  load_env "$name"

  if [ -f "Dockerfile" ]; then
    # Tag current image for rollback before building new one
    old_id=$(docker images -q "$name" 2>/dev/null | head -1)
    if [ -n "$old_id" ]; then
      local ts
      ts=$(date +%s)
      docker tag "$old_id" "${name}:previous-${ts}" 2>/dev/null || true
      info "saved current image as ${name}:previous-${ts} for rollback"
    fi

    if [ -f "docker-compose.yml" ]; then
      docker compose up --build -d
    else
      docker build -t "$name" .
      port=$(get_app_port "$name")
      docker run -d --restart unless-stopped --name "$name" \
        -p "$port:$port" \
        --env-file "${ENV_DIR}/${name}.env" 2>/dev/null \
        "$name"
    fi
    pid=$(docker ps -q -f name="$name" 2>/dev/null)
    if [ -n "$pid" ]; then
      ok "deployed $name -> https://$name.$BASE_DOMAIN"
    else
      err "deployment failed for $name"
      exit 1
    fi
  else
    docker compose up --build -d
    ok "deployed $name -> https://$name.$BASE_DOMAIN"
  fi
}

cmd_rollback() {
  local name=$1
  [ -z "$name" ] && { err "Usage: deploy rollback <name>"; exit 1; }
  path=$(get_path "$name")
  [ -z "$path" ] && { err "app '$name' not found"; exit 1; }
  type=$(get_type "$name")

  if [ "$type" != "docker" ]; then
    warn "rolling back $name to previous git state..."
    cd "$path"
    if git log --oneline -2 2>/dev/null | tail -1; then
      cmd_stop "$name" 2>/dev/null || true
      git checkout HEAD~1 -- . 2>/dev/null && {
        ok "reverted code to previous commit"
        cmd_start "$name" "-d"
      } || err "no previous commit to rollback to"
    else
      err "not a git repository — cannot rollback"
      exit 1
    fi
  else
    warn "rolling back $name to previous docker image..."
    prev_tag=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "^${name}:" | grep -v latest | sort | tail -1 2>/dev/null)
    if [ -z "$prev_tag" ]; then
      err "no previous image found for $name"
      exit 1
    fi
    cmd_stop "$name" 2>/dev/null || true
    port=$(get_app_port "$name")
    docker run -d --restart unless-stopped --name "$name" \
      -p "$port:$port" \
      --env-file "${ENV_DIR}/${name}.env" 2>/dev/null \
      "$prev_tag" && ok "rolled back $name to $prev_tag" || err "rollback failed"
  fi
}

cmd_ssl() {
  local name=$1
  [ -z "$name" ] && { err "Usage: deploy ssl <name>"; exit 1; }
  if ! command -v certbot &>/dev/null; then
    err "certbot is required. Install it: apt install certbot python3-certbot-nginx"
    exit 1
  fi
  grep -q "^$name\t" "$REGISTRY" 2>/dev/null || { err "app '$name' not found"; exit 1; }
  info "provisioning SSL for ${name}.${BASE_DOMAIN}..."
  sudo certbot --nginx -d "${name}.${BASE_DOMAIN}" --non-interactive --agree-tos --register-unsafely-without-email 2>&1 || {
    warn "certbot failed. Try: sudo certbot --nginx -d ${name}.${BASE_DOMAIN}"
    exit 1
  }
  ok "SSL provisioned for ${name}.${BASE_DOMAIN}"
  grep -q "^SSL_CERT=" "$DEPLOY_CONF" 2>/dev/null || {
    echo "SSL_CERT=/etc/letsencrypt/live/${name}.${BASE_DOMAIN}/fullchain.pem" >> "$DEPLOY_CONF"
    echo "SSL_KEY=/etc/letsencrypt/live/${name}.${BASE_DOMAIN}/privkey.pem" >> "$DEPLOY_CONF"
    info "updated $DEPLOY_CONF with SSL cert paths"
  }
}

cmd_ssl_renew() {
  info "renewing all Let's Encrypt certificates..."
  if command -v certbot &>/dev/null; then
    sudo certbot renew && sudo nginx -s reload && ok "certificates renewed and nginx reloaded"
  else
    err "certbot is required. Install it: apt install certbot python3-certbot-nginx"
    exit 1
  fi
}

cmd_uninstall() {
  warn "This will stop all apps and remove deploy data from $DEPLOY_HOME"
  echo -n "Are you sure? [y/N] "; read -r confirm
  [ "$confirm" != "y" ] && [ "$confirm" != "Y" ] && { info "cancelled"; exit 0; }

  # Stop all apps
  while IFS= read -r line; do
    [[ "$line" =~ ^# || -z "$line" ]] && continue
    name=$(echo "$line" | awk '{print $1}')
    cmd_stop "$name" 2>/dev/null || true
  done < "$REGISTRY"

  # Remove nginx config
  if [ -f "$NGINX_CONF" ]; then
    sudo rm -f "$NGINX_CONF" && ok "removed nginx config"
    sudo nginx -s reload 2>/dev/null || true
  fi

  rm -rf "$DEPLOY_HOME"
  ok "removed $DEPLOY_HOME"
  ok "deploy uninstalled"
}

# ── dev:init — scaffold new project ────────────────────────────────────────────

cmd_dev_init() {
  local name=$1 template=$2
  [ -z "$name" ] && { err "Usage: deploy dev:init <name> <template>"; exit 1; }
  [ -z "$template" ] && template="flask"

  local dir="$PWD/$name"
  [ -d "$dir" ] && { err "directory '$dir' already exists"; exit 1; }

  mkdir -p "$dir"
  info "scaffolding '$name' ($template) in $dir..."

  case "$template" in
    flask)
      cat > "$dir/app.py" << 'PYEOF'
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello from deploy!"

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
PYEOF
      echo "flask" > "$dir/requirements.txt"
      ;;

    express|node)
      cat > "$dir/package.json" << 'PKGJSON'
{
  "name": "$name",
  "scripts": {
    "start": "node index.js",
    "dev": "node --watch index.js"
  }
}
PKGJSON
      cat > "$dir/index.js" << 'JSEOF'
const http = require('http');
const port = process.env.PORT || 3000;
http.createServer((req, res) => {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello from deploy!\n');
}).listen(port, () => console.log(`listening on ${port}`));
JSEOF
      ;;

    static)
      cat > "$dir/index.html" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>${name}</title></head>
<body><h1>Hello from deploy!</h1></body>
</html>
HTMLEOF
      ;;

    *)
      err "unknown template: $template"
      echo "supported: flask, express, node, static"
      exit 1
      ;;
  esac

  # Generate deploy.yml
  cat > "$dir/deploy.yml" << YMLEOF
name: ${name}
type: ${template}
YMLEOF

  # Register if deploy is initialized
  if [ -f "$REGISTRY" ]; then
    cmd_add "$name" "$template" "$dir" 2>/dev/null || true
  fi

  ok "scaffolded $name ($template) in $dir"
  echo "  cd $dir"
  echo "  deploy dev $name"
  echo "  deploy start $name -d"
}

# ── dev:logs — tail dev logs ──────────────────────────────────────────────────

cmd_dev_logs() {
  local name=$1
  [ -z "$name" ] && { err "Usage: deploy dev:logs <name>"; exit 1; }

  local log_file="${LOG_DIR}/${name}.dev.log"
  if [ ! -f "$log_file" ]; then
    # Check for main log as fallback
    log_file="${LOG_DIR}/${name}.log"
    [ ! -f "$log_file" ] && { err "no dev logs found for $name (start dev mode first)"; exit 1; }
  fi

  info "watching dev logs for $name (Ctrl+C to stop)..."
  tail -f "$log_file"
}

# ── dev:url — show or open dev URL ────────────────────────────────────────────

cmd_dev_url() {
  local name=$1 open_browser=${2:-}
  [ -z "$name" ] && { err "Usage: deploy dev:url <name> [--open]"; exit 1; }

  local url="https://${name}.${DEV_DOMAIN}"
  # Also check if a dev port is assigned (confirms dev mode is running)
  local dev_port
  dev_port=$(get_app_field "$name" "dev_port" 2>/dev/null)
  local dev_enabled
  dev_enabled=$(get_app_field "$name" "dev" 2>/dev/null)

  echo "$url"
  if [ "$dev_enabled" = "true" ] && [ -n "$dev_port" ]; then
    echo "  (dev mode on port $dev_port)"
  fi

  if [ "$open_browser" = "--open" ] || [ "$open_browser" = "-o" ]; then
    if command -v xdg-open &>/dev/null; then
      xdg-open "$url" 2>/dev/null && ok "opened $url" || warn "could not open browser"
    elif command -v open &>/dev/null; then
      open "$url" 2>/dev/null && ok "opened $url" || warn "could not open browser"
    else
      warn "no browser opener found (xdg-open/open). URL: $url"
    fi
  fi
}

# 'nginx' and 'custom' are called directly by the dispatcher via regen_nginx
# and inline code in bin/deploy
